version: '2'
services:
  qedb_admin:
    image: qedb-admin:latest
    container_name: 'qedb_admin'
    environment:
      # - URL=https://admin.qedb.net
      - NODE_ENV=production
      # - DATABASE_HOST=my_mysql
      # - DATABASE_PORT=3306
      # - DATABASE_PASSWORD=xyz
      # - ADMIN_JWT_SECRET=xyz
    # volumes:
    #   - /root/public_files:/usr/src/app/public
    # depends_on:
    #   - my_mysql
    networks:
      - mynetwork
    ports:
      - 4000:4000
  qedb_client:
    image: qedb-client:latest
    container_name: 'qedb_client'
    environment:
      - NODE_ENV=production
      # - NEXT_TELEMETRY_DISABLED=1
      # - NEXTAUTH_URL=https://my-website
      # - NEXT_PUBLIC_API_URL=https://my-website/gapi
    # depends_on:
      # - gyanmail_api
    networks:
      - mynetwork
    ports:
      - 3000:3000
  qedb_server:
    image: qedb-server:latest
    container_name: 'qedb_server'
    environment:
      - NODE_ENV=production
      - PORT=9000
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://krowdee:Krowdee477@qdb-krowdee.qt3cr.mongodb.net/edufunda
      - AWS_ACCESS_KEY=AKIAXB2ZI6H727Q2Z66I
      - AWS_SECRET_KEY=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
      - S3_FILEUPLOAD_BUCKET=adagiri-test-bucket
      - SMS_HANDLER=aws_sns
      - JWT_SECRET=edu910239funda939302idsk
      - JWT_COOKIE_EXPIRE=30
      - JWT_EXPIRE=90d
      - CLIENT_URL=https://qedb.net
    # depends_on:
      # - gyanmail_api
    networks:
      - mynetwork
    ports:
      - 9000:9000

  qedb_nginx:
    image: qedb-nginx:latest
    container_name: 'qedb_nginx'
    networks:
      - mynetwork
    ports:
      - 8090:8090
      - 8000:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /root/data/certbot/www:/var/www/certbot
    # depends_on:
      # - mymail_api
      # - mymail_ui
networks:
  mynetwork:
    driver: bridge
